#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# Description: Build Kernel using GitHub Actions
# Change from P3TERX
#

name: gtest library build
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "45 14 * * *"


env:
  REPO_URL: https://github.com/google/googletest
  REPO_BRANCH: main
  UPLOAD_DIR: false
  UPLOAD_RELEASE: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  update_config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list   
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bzip2 gawk git patch unzip htop wget curl -y
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo mkdir -p /workdir/upload
        sudo chown $USER:$GROUPS /workdir
        sudo chown $USER:$GROUPS /workdir/upload

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH googletest

    - name: Build
      id: update
      working-directory: /workdir
      run: |
        mkdir -p $GITHUB_WORKSPACE/gtest_lib
        sudo chown $USER:$GROUPS $GITHUB_WORKSPACE/gtest_lib
        echo $GITHUB_WORKSPACE
        mkdir -p googletest/build
        cd googletest/build
        cmake build ..
        cmake --build .
        cd lib
        cp -fr *.a $GITHUB_WORKSPACE/gtest_lib/
        echo "::set-output name=status::success"

    - name: Commit files
      continue-on-error: true
      # if: steps.update.outputs.status == 'success'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        cd $GITHUB_WORKSPACE
        git add .
        git commit -m "Update gtest library" -a

    - name: Push changes
      continue-on-error: true
      # if: steps.update.outputs.status == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}
