#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# Description: Build Kernel using GitHub Actions
# Change from P3TERX
#

name: Manjaro update config

on:
#   workflow_dispatch:
  schedule:
    #- cron: "36 20 * * 2,6"
    - cron: "45 14 * * *"
   # inputs:
    #  ssh:
     #   description: 'SSH connection to Actions'
      #  required: false
       # default: 'false'

env:
  UPLOAD_DIR: false
  UPLOAD_RELEASE: true
  TZ: Asia/Ho_Chi_Minh

jobs:
  update_config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list   
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bzip2 gawk git patch unzip htop wget curl -y
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo mkdir -p /workdir/upload
        sudo chown $USER:$GROUPS /workdir
        sudo chown $USER:$GROUPS /workdir/upload

    - name: Update
      id: update
      working-directory: /workdir
      run: |
        # echo "$(curl https://gitlab.manjaro.org/packages/core/linux510/-/raw/master/config)" > config
        # echo "$(curl https://gitlab.manjaro.org/packages/core/linux510/-/raw/master/config.anbox)" > config.anbox
        wget -O config https://gitlab.manjaro.org/packages/core/linux515/-/raw/master/config
        #wget -O config.anbox https://gitlab.manjaro.org/packages/core/linux510/-/raw/master/config.anbox
        config=/home/runner/work/Linux_kernel_pre_built/Linux_kernel_pre_built/config_manjaro
        sudo rm -rf ${config}
        sudo cat config > config_manjaro
        #sudo cat config.anbox >> config_manjaro
        sudo mv config_manjaro ${config}

        echo "::set-output name=status::success"

    - name: Commit files
      continue-on-error: true
      # if: steps.update.outputs.status == 'success'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add changes" -a

    - name: Push changes
      continue-on-error: true
      # if: steps.update.outputs.status == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}
